spring:
  redis:
    host: xxx
    port: 6379
    password: 1234
    database: 14
    timeout: 2000
  datasource:
    url: jdbc:mysql://xxx:xxx/xxx?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 1234
    hikari:
      connectionTimeout: 5000
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 300000
      maxLifetime: 1200000
mybatis:
  mapper-locations: classpath:mappers/*.xml